version: 1.0.{build}
image: Visual Studio 2017
platform: x86
configuration: Debug

  

before_build: 
    - ps: Set-Location "C:/projects/silkwrappernetest/PS"
    - ps: ./Build_PDFium.ps1 -Arch "$env:PLATFORM"

    - ps: Set-Location "C:/projects/silkwrappernetest/PS"
    - ps: ./Build_Wrapper.ps1 -Arch "$env:PLATFORM"

    - ps: Set-Location C:/projects/silkwrappernetest
    - dotnet restore C:/projects/silkwrappernetest/SilkWrapperNETest/SilkWrapperNETest.csproj

build:
  include_nuget_references: true
  verbosity: normal
  project: SilkWrapperNETest.sln 

test_script:
  - C:\projects\silkwrappernetest\SilkWrapperNETest\bin\x86\Debug\SilkWrapperNETest.exe