version: 1.0.{build}
image: Visual Studio 2017
platform: x64
configuration: Debug

before_build: 
    - ps: Set-Location "C:/projects/silkwrappernetest/PS"
    - ps: ./Build_PDFium.ps1 -Arch "$env:PLATFORM"

    - ps: Set-Location "C:/projects/silkwrappernetest/PS"
    - ps: ./Build_Wrapper.ps1 -Arch "$env:PLATFORM"

    # This is the location for building the VS project
    - ps: Set-Location C:/projects/silkwrappernetest

    #- dotnet restore

build:
  include_nuget_references: true
  verbosity: normal
  project: SilkWrapperNETest.sln 

test_script:
  - C:\projects\silkwrappernetest\SilkWrapperNETest\bin\x64\Debug\SilkWrapperNETest.exe